name: "Fake annotator"
on:
  pull_request:
  push:
    branches: [main]

jobs:
  annotator:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      COMPOSER_NO_INTERACTION: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fake
        run: |
          echo ::notice \
            file=$PWD/src/Hugger/Friendly.php,line=1,col=0::this is a notice
          echo ::warning \
            file=$PWD/src/Hugger/Friendly.php,line=1,col=0::this is a warning
          echo ::error \
            file=$PWD/src/Hugger/Friendly.php,line=1,col=0::this is a error
          exit 1
