name: "PHPInsights"
on:
  pull_request:
  push:
    branches: [main]

jobs:
  phpinsights:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PHPInsights
        uses: docker://nunomaduro/phpinsights
        with:
          args: --format=github-action
