name: "PHPStan"
on:
  pull_request:
  push:
    branches: [main]

jobs:
  php-stan:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      COMPOSER_NO_INTERACTION: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2

      - name: Cache vendor
        id: cache-composer-vendor
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-vendor--${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        if: steps.cache-composer-vendor.outputs.cache-hit != 'true'
        run: composer install --prefer-dist

      - name: Execute PHPStan
        run: php vendor/bin/phpstan analyse src --level 8 --error-format=github
